version: '3'

tasks:

  install-libs:
    cmds:
      - task: _install-traq-extensions
      - task: _install-traq-aot

  _install-traq-extensions:
    internal: true
    dir: libs
    cmds:
      - git clone git@github.com:YuHima03/dotnet-traq-extensions.git
      - cd dotnet-traq-extensions && git checkout feat/message-extensions

  _install-traq-aot:
    internal: true
    dir: libs
    cmds:
      - git clone git@github.com:YuHima03/dotnet-traq.git
      - cd dotnet-traq && git checkout aot

  update-libs:
    dir: libs
    cmds:
      - cd dotnet-traq-extensions && git pull
      - cd dotnet-traq && git pull

  dev-up:
    cmds:
    - docker compose up -d --build

  dev-down:
    cmds:
    - docker compose down

  dev-restart:
    cmds:
    - docker compose build
    - task: down
    - task: up
