version: '3'

tasks:

  build:
    desc: Build the docker image of the project.
    cmds:
      - task: ef-precompile
      - docker compose build bot --no-cache

  up:
    desc: Start the docker containers of the project.
    cmds:
      - docker compose up -d

  down:
    desc: Stop the docker containers of the project.
    cmds:
      - docker compose down

  ef-precompile:
    desc: Precompiles model types used by the DbContext class for Native AOT compilation.
    sources:
      - "{{.TASKFILE_DIR}}/src/BotTidus.Infrastructure/Repository/*Repository.cs"
    generates:
      - "{{.TASKFILE_DIR}}/src/BotTidus.Infrastructure/Repository/Compiled/*.g.cs"
    dir: .
    cmds:
      - rm -f src/BotTidus.Infrastructure/Repository/Compiled/*.g.cs
      - |
        dotnet ef dbcontext optimize \
          --project         src/BotTidus.Infrastructure \
          --startup-project src/BotTidus \
          --output-dir      Repository/Compiled \
          --context         BotTidus.Infrastructure.Repository.BotDbContext \
          --namespace       BotTidus.Infrastructure.Repository \
          --suffix          ".g" \
          --precompile-queries \
          --nativeaot

  ef-scaffold:
    desc: Scaffold a new DbContext and entity types based on the current database schema.
    dir: .
    sources:
      - "{{.TASKFILE_DIR}}/db/init/0_schema.sql"
    generates:
      - "{{.TASKFILE_DIR}}/src/BotTidus.Infrastructure/Repository/*.cs"
    dotenv:
      - .env
    cmds:
      - echo "Scaffolding from $NS_MARIADB_HOSTNAME:$NS_MARIADB_PORT/$NS_MARIADB_DATABASE"
      - |
        dotnet ef dbcontext scaffold \
          "Server=$NS_MARIADB_HOSTNAME;Port=$NS_MARIADB_PORT;Database=$NS_MARIADB_DATABASE;User Id=$NS_MARIADB_USER;Password=$NS_MARIADB_PASSWORD;" \
          "Pomelo.EntityFrameworkCore.MySql" \
          --project src/BotTidus.Infrastructure \
          --output-dir Repository \
          --context BotDbContext \
          --data-annotations \
          --no-onconfiguring
