// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using BotTidus.RepositoryImpl.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BotTidus.RepositoryImpl.CompiledModels
{
    public static class DiscordWebhookUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(DiscordWebhook @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(DiscordWebhook @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsEnabled>k__BackingField")]
        public static extern ref bool IsEnabled(DiscordWebhook @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NotifiesOnFlags>k__BackingField")]
        public static extern ref int NotifiesOnFlags(DiscordWebhook @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PostUrl>k__BackingField")]
        public static extern ref string PostUrl(DiscordWebhook @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(DiscordWebhook @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref Guid UserId(DiscordWebhook @this);
    }
}
