// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using BotTidus.RepositoryImpl.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BotTidus.RepositoryImpl.CompiledModels
{
    public static class MessageFaceScoreUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MessageId>k__BackingField")]
        public static extern ref Guid MessageId(MessageFaceScore @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(MessageFaceScore @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NegativePhraseCount>k__BackingField")]
        public static extern ref uint NegativePhraseCount(MessageFaceScore @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NegativeReactionCount>k__BackingField")]
        public static extern ref uint NegativeReactionCount(MessageFaceScore @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PositivePhraseCount>k__BackingField")]
        public static extern ref uint PositivePhraseCount(MessageFaceScore @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PositiveReactionCount>k__BackingField")]
        public static extern ref uint PositiveReactionCount(MessageFaceScore @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(MessageFaceScore @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref Guid UserId(MessageFaceScore @this);
    }
}
