// <auto-generated />
using BotTidus.RepositoryImpl;
using BotTidus.RepositoryImpl.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(Repository), typeof(RepositoryModel))]
