// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using BotTidus.RepositoryImpl.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BotTidus.RepositoryImpl.CompiledModels
{
    public static class RepoUserFaceCountUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NegativePhraseCount>k__BackingField")]
        public static extern ref uint NegativePhraseCount(RepoUserFaceCount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NegativeReactionCount>k__BackingField")]
        public static extern ref uint NegativeReactionCount(RepoUserFaceCount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PositivePhraseCount>k__BackingField")]
        public static extern ref uint PositivePhraseCount(RepoUserFaceCount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PositiveReactionCount>k__BackingField")]
        public static extern ref uint PositiveReactionCount(RepoUserFaceCount @this);
    }
}
